#!/bin/sh

# $Id$
#
# Note: you will need to set your CVSROOT to the tamjb project's root,
# and log in! 

# Configuration: Either generate a key for buildling the byteheaven
# packages here, or whatever:

KEYFILE=$HOME/.byteheaven.snk

# Well, here, build this one.

# Wed Dec 15 01:21:10 PST 2004
PACKAGE_DIR=tamjb-1_0_0
PACKAGE_TAG=REL_1_0_0

if [ -d $PACKAGE_DIR ] ; then 
  echo "Package dir ${PACKAGE_DIR} exists! Bailing"
  exit 1
fi

if [ -d $PACKAGE_DIR-bin ] ; then 
  echo "Package dir ${PACKAGE_DIR}-bin exists! Bailing"
  exit 1
fi

mkdir $PACKAGE_DIR

# Get the package
( cvs get -r $PACKAGE_TAG -d ${PACKAGE_DIR} tamjb ) || exit 1

# Zip up the source
zip -r $PACKAGE_DIR-src.zip $PACKAGE_DIR || exit 1

# Compile
ln -s "$KEYFILE" "${PACKAGE_DIR}/assykey.snk" || exit 1
( cd $PACKAGE_DIR && make  ) || exit 1
( cd $PACKAGE_DIR && make rel-binary  ) || exit 1

# Zip up the binary
mv $PACKAGE_DIR/package $PACKAGE_DIR-bin
zip -r $PACKAGE_DIR-bin.zip $PACKAGE_DIR-bin || exit 1

echo "Success!"


