/// \file
/// $Id$
///
/// A database of information about "playable files". Currently
/// this is only mp3 files, but, well...why constrain yourself?
///

// Copyright (C) 2004 Tom Surace.
//
// This file is part of the Tam Jukebox project.
//
// This program is free software; you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation; either version 2 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program; if not, write to the Free Software
// Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
//
// Feel free to track down and contact ALL project contributors to
// negotiate other terms. Bring a checkbook.
//
//   Tom Surace <tekhedd@byteheaven.net>

using System;
using System.Collections;
using System.Data;
using System.Diagnostics;
using System.IO;                // Directory functions
using System.Text.RegularExpressions;
using System.Text;
using Mono.Data.SqliteClient;

///
/// File information database namespace
///

namespace tam.LocalFileDatabase
{
   ///
   /// The database class wraps all accesses to our local file database.
   ///
   public class StatusDatabase
   {
      ///
      /// Creates the database wrapper.
      ///
      /// \param dbConnectionString connection string for our database. 
      ///
      public StatusDatabase( string dbConnectionString )
      {
         _Trace( "StatusDatabase" );

         _connectionString = dbConnectionString;

      }

      ~StatusDatabase()
      {
         _Trace( "~StatusDatabase" );
      }

      /// 
      /// Function that creates the necessary tables. If necessary.
      ///
      public void CreateTablesIfNecessary()
      {
         _CreateStatusTable();
         _CreateAttributeTable();
      }

      ///
      /// Create the status table
      ///
      void _CreateStatusTable()
      {
         IDbConnection dbcon = _GetDbConnection();
         IDbCommand cmd = dbcon.CreateCommand();

         // Create a table to hold info derived from the files' own 
         // header info:
         string query = 
            "CREATE TABLE file_info ( " +
            "  key INTEGER PRIMARY KEY NOT NULL," +
            "  file_path TEXT," +
            "  artist VARCHAR(256)," +
            "  album VARCHAR(256)," +
            "  title VARCHAR(256)," +
            "  track INTEGER," +
            "  genre VARCHAR(80)," +
            "  length_seconds INTEGER" +
            "  )";

         cmd.CommandText = query;
         int affected = cmd.ExecuteNonQuery();
         cmd.Dispose();
         dbcon.Dispose();
      }

      /// 
      /// Function that creates the attribute table
      ///
      /// \todo CREATE INDEX on the attribute table as appropriate
      ///
      void _CreateAttributeTable()
      {
         // Create the Attribute table
         IDbConnection dbcon = _GetDbConnection();
         IDbCommand cmd = dbcon.CreateCommand();

         // Create a table to hold info derived from the files' own 
         // header info:
         //   statuskey - refers to file_info.key autogenerated unique
         //     btree index
         //   playlist_key - index of playlist
         //   value - measure of how appropriate this song is to the
         //     playlist, from 0 to 10000 inclusive. (100.00 percent)
         //
         string query = 
            "CREATE TABLE track_attribute ( " +
            "  track_ref    INTEGER NOT NULL," +
            "  playlist_key INTEGER NOT NULL," +
            "  value        INTEGER NOT NULL" +
            "  )";

         cmd.CommandText = query;
         cmd.ExecuteNonQuery();
         cmd.Dispose();

         // Create an index on the very popular track_ref and playlist_key
         // fields

         cmd = dbcon.CreateCommand();

         // Create a table to hold info derived from the files' own 
         // header info:
         //   statuskey - refers to file_info.key autogenerated unique
         //     btree index
         //   playlist_key - index of playlist
         //   value - measure of how appropriate this song is to the
         //     playlist, from 0 to 10000 inclusive. (100.00 percent)
         //
         query = 
            "CREATE INDEX track_ix ON"
            + " track_attribute ( track_ref )"
            ;

         cmd.CommandText = query;
         cmd.ExecuteNonQuery();
         cmd.Dispose();


         cmd = dbcon.CreateCommand();

         // Create a table to hold info derived from the files' own 
         // header info:
         //   statuskey - refers to file_info.key autogenerated unique
         //     btree index
         //   playlist_key - index of playlist
         //   value - measure of how appropriate this song is to the
         //     playlist, from 0 to 10000 inclusive. (100.00 percent)
         //
         query = 
            "CREATE INDEX playlist_ix ON"
            + " track_attribute ( playlist_key )"
            ;

         cmd.CommandText = query;
         cmd.ExecuteNonQuery();
         cmd.Dispose();

         dbcon.Dispose();
      }

      ///
      /// Add an entry to the database
      ///
      /// \throw (any) Runtime error on various database failures.
      ///
      /// This does not check for duplicate entries.
      ///
      public void Add( PlayableData newData )
      {
         AddFileInfo( newData );

         /// \todo make a guess at the file's attributes from the ID3 info:
         ///
      }

      public PlayableData GetFileInfo( uint key )
      {
         string query = 
            "SELECT file_path, artist, album, title, track," +
            + " genre, length_seconds" 
            + " FROM file_info"
            + " WHERE key = " + key
            ;

         uint value;
         IDbConnection dbcon = null;
         IDbCommand cmd = null;
         IDataReader reader = null;
         try
         {
            dbcon = _GetDbConnection();
            cmd = dbcon.CreateCommand();
            cmd.CommandText = query;
            reader = cmd.ExecuteReader();

            PlayableData returnData;
            if (!reader.Read())
            {
               // Nothing returned. This is bad!
               throw new Exception( "No data returned from query" );
            }
            else
            {
               returnData = new PlayableData();
               returnData.key = key;
               returnData.filePath = reader.GetString(0); // works for TEXT fld
               returnData.artist = reader.GetValue(1).ToString();
               returnData.album = reader.GetValue(2).ToString();
               returnData.title = reader.GetValue(3).ToString();
               returnData.track = reader.GetInt32(4);
               returnData.genre = reader.GetValue(5).ToString();
               returnData.lengthInSeconds = reader.GetInt32(6);
            }

            return returnData;
         }
         catch (Exception e)
         {
            throw new ApplicationException( "Query failed: " + query, e );
         }
         finally
         {
            if (null != reader)
               reader.Close();

            if (null != cmd)
               cmd.Dispose();

            if (null != dbcon)
               dbcon.Dispose();
         }
      }

      ///
      /// \note The key field of newData is ignored for obvious reasons
      ///
      void AddFileInfo( PlayableData newData )
      {
         _lastModified = DateTime.Now;

         // Create a table to hold info derived from the files' own 
         // header info:
         string query = 
            "INSERT INTO file_info " +
            " ( " +
            "  key," +          // insert NULL for autoincrement
            "  file_path," +
            "  artist," +
            "  album," +
            "  title," +
            "  track," +
            "  genre," +
            "  length_seconds" +
            "  )" +
            " VALUES ( " +
            "  NULL," +
            "  '" + _StripEvil( newData.filePath ) + "'," +
            "  '" + _StripEvil( newData.artist ) + "'," +
            "  '" + _StripEvil( newData.album ) + "'," +
            "  '" + _StripEvil( newData.title ) + "'," +
            "  '" + newData.track + "'," +
            "  '" + _StripEvil( newData.genre ) + "'," +
            "  0" +
            "  )";

         IDbConnection dbcon = null;
         IDbCommand cmd = null;
         try
         {
            dbcon = _GetDbConnection();
            cmd = dbcon.CreateCommand();
            cmd.CommandText = query;
            cmd.ExecuteNonQuery();
         }
         catch (Exception e)
         {
            // Pass along the exception with the query added
            throw new ApplicationException( "Query failed: " + query, e );
         }
         finally
         {
            if (null != cmd)
               cmd.Dispose();

            if (null != dbcon)
               dbcon.Dispose();
         }
      }

      // This allows single-tics ("'") because they are filtered separately
      // by tickRegex.
      Regex _invalidCharRegex = new Regex( "[^\\'A-Za-z /!@#$%^&*()-_+=?~]" );
      Regex _tickRegex = new Regex( "'" );

      ///
      /// Removes any special chars from the supplied string, to
      /// avoid cryptic SQL errors.
      ///
      /// Also, escape any single-tick characters.
      ///
      /// \todo Find out why special characters (other than single-tick)
      ///   cause SQLite to
      ///   throw exceptions and replace this regex workaround that
      ///   isn't very friendly to non-english-language users.
      ///
      string _StripEvil( string impureString )
      {
         string firstResult = _invalidCharRegex.Replace( impureString, " " );
         string secondResult = _tickRegex.Replace( firstResult, "''" );

         return secondResult;
      }

      ///
      /// selects one song at random based on the supplied playlist
      /// limitations:
      ///
      /// \param criteria Song seletion criteria (aside from random)
      /// \param key Unique key of the file that is chosen
      ///
      /// \return Total number of tracks in this playlist. If 0, the
      ///   output string track will be empty.
      ///
      public uint PickRandom( ref PlaylistCriteria criteria,
                              out uint   key )
      {
         Debug.Assert( null != criteria ); // parameter required

         key = 0;

         _UpdateTrackCache( ref criteria );

         // 
         // First, how many tracks match this query?
         //
         uint count = criteria.matchCount;
         if (count < 1)
            return count;       // ** quick exit **

         //
         // Pick an entry at random and retrieve it
         //
         uint offset = (uint)_rng.Next( 0, (int)count );

         _Trace( "Choosing track: " + offset );

         string query = 
            _BuildFullQuery( criteria )
            + " LIMIT 1 OFFSET " + offset
            ;
         
         IDbConnection dbcon = null;
         IDbCommand cmd = null;
         IDataReader reader = null;
         try
         {
            _Trace( query );

            dbcon = _GetDbConnection();
            cmd = dbcon.CreateCommand();
            cmd.CommandText = query;

            reader = cmd.ExecuteReader();
            if (!reader.Read())
            {
               // Nothing returned. This is bad!
               throw new Exception( "No data returned from query" );
            }
            else
            {
               key = (uint)reader.GetInt32(0);
            }
         }
         catch (Exception e)
         {
            throw new ApplicationException( "Query failed: " + query, e );
         }
         finally
         {
            if (null != reader)
               reader.Close();

            if (null != cmd)
               cmd.Dispose();

            if (null != dbcon)
               dbcon.Dispose();
         }

         return count;
      }

      ///
      /// \return the number of entries in the playlist indexed by
      ///   key.
      ///
      public uint GetRowCount( PlaylistCriteria criteria )
      {
         // Wrap the count query in a count clause, see?
         string query =
            "SELECT count(*) from ( " 
            + _BuildFullQuery( criteria )
            + " )";

         IDbConnection dbcon = null;
         IDbCommand cmd = null;
         try
         {
            _Trace( query );

            dbcon = _GetDbConnection();
            cmd = dbcon.CreateCommand();
            cmd.CommandText = query;

            // Returns the first parameter, the number of rows:
            object countObj = cmd.ExecuteScalar();
            uint count = Convert.ToUInt32( countObj );

            return count;
         }
         catch (Exception e)
         {
            throw new ApplicationException( "Query failed: " + query, e );
         }
         finally
         {
            if (null != cmd)
               cmd.Dispose();

            if (null != dbcon)
               dbcon.Dispose();
         }
      }

      string _BuildFullQuery( PlaylistCriteria criteria )
      {
         if (criteria.Count == 0)
         {
            // Just play any file (no limiting criteria)
            return "SELECT key FROM file_info";
         }

         StringBuilder query = new StringBuilder( "" );

         bool first = true;
         foreach (DictionaryEntry de in criteria)
         {
            PlaylistCriterion crit = (PlaylistCriterion)de.Value;
            if (!first)
               query.Append( " INTERSECT " );
            else
               first = false;
            
            query.Append( _BuildPartialQuery( crit ) );
         }
         return query.ToString();
      }

      ///
      /// Build one part of a compound SELECT. This means no LIMIT,
      /// ORDER BY, etc will be in the returned query.
      ///
      string _BuildPartialQuery( PlaylistCriterion criterion )
      {
         // Restrict the criteria first, because they'll return the smallest
         // number of rows (smaller than the join anyway).
         string query = 
            "SELECT track_attribute.track_ref"
            + " FROM track_attribute"
            + " WHERE track_attribute.playlist_key = " + criterion.attribKey
            + " AND track_attribute.value >= " + criterion.value
            ;

         /// 
         /// \todo Implment the range checking required to enforce attribute

         return query.ToString();
      }

      ///
      /// A function that imports data from the local-file info table
      /// (file_info) into a playlist's attribute table (track_attribute).
      ///
      /// \param attribKey Unique index of the attribute table
      /// \param initValue Initial attribute value
      ///
      public void ImportNewFiles( uint attribKey, int initValue )
      {
         _lastModified = DateTime.Now;

         // Find every row in file_info for which there is no corresponding
         // entry in track_attribute, and insert the results into 
         // track_attribute.

         string query = 
            "INSERT INTO track_attribute "
            + " ( "
            + " track_ref,"
            + " playlist_key,"
            + " value"
            + " )"
            + " SELECT"
            + " file_info.key,"
            + attribKey + ","
            + initValue
            + " FROM file_info"
            + " EXCEPT SELECT "
            + " track_ref,"
            + attribKey + ","
            + initValue
            + " FROM track_attribute "
            + " WHERE track_attribute.playlist_key = " + attribKey
            ;

         _Trace( query );
         _ExecuteNonQuery( query );
      }

      ///
      /// Get the value of the attribute of a particular playlist
      /// for a particular track.
      ///
      public uint GetAttribute( uint playlistKey,
                                uint trackKey )
      {
         string query = 
            "SELECT value FROM track_attribute"
            + " WHERE playlist_key = " + playlistKey
            + " AND track_ref = " + trackKey
            ;

         uint value;
         IDbConnection dbcon = null;
         IDbCommand cmd = null;
         IDataReader reader = null;
         try
         {
            dbcon = _GetDbConnection();
            cmd = dbcon.CreateCommand();
            cmd.CommandText = query;

            reader = cmd.ExecuteReader();
            if (!reader.Read())
            {
               // Nothing returned. This is bad!
               throw new Exception( "No data returned from query" );
            }
            else
            {
               value = (uint) reader.GetInt32(0);
            }
         }
         catch (Exception e)
         {
            throw new ApplicationException( "Query failed: " + query, e );
         }
         finally
         {
            if (null != reader)
               reader.Close();

            if (null != cmd)
               cmd.Dispose();

            if (null != dbcon)
               dbcon.Dispose();
         }

         return value;
      }

      public void SetAttribute( uint playlistKey,
                                uint trackKey,
                                uint newValue )
      {
         string query = 
            "UPDATE track_attribute "
            + " SET value = " + newValue
            + " WHERE playlist_key = " + playlistKey
            + " AND track_ref = " + trackKey
            ;

         _lastModified = DateTime.Now;
         _ExecuteNonQuery( query );
      }

      ///
      /// Function that scans recursively below the named dir for mp3 files.
      /// This updates the local file information for all matching files
      /// in the local database. This may take a very long time.
      ///
      /// \param root Top level directory to recursively search
      ///
      /// \todo This belongs in a separate class or something.
      ///
      /// \todo Should the root parameter be absolute?
      ///
      /// \todo Handle other than just mp3 files
      ///
//       public void Scan( string root )
//       {
//          Trace.WriteLine( "dir> " + root );

//          // Note: insert all files in a subdirectory as a single
//          //   transaction to reduce the number of times we have to
//          //   wait for disk writes.
//          _ExecuteNonQuery( "BEGIN" );
//          try
//          {
//             // Check all files in this dir
//             DirectoryInfo dirInfo = new DirectoryInfo( root );
//             FileInfo [] filez = dirInfo.GetFiles();
//             string mp3string = "mp3";
//             foreach (FileInfo info in filez)
//             {
//                // Compare extension (case-insensitive) to 'mp3'
//                if (info.FullName.ToLower().EndsWith( "mp3"))
//                {
//                   _UpdateMP3FileInfo( info );
//                }
//             }
//             _ExecuteNonQuery( "COMMIT" );
//          }
//          catch
//          {
//             _ExecuteNonQuery( "ROLLBACK" );
//             throw;
//          }

//          // Scan all subdirs
//          string [] subdirs = Directory.GetDirectories( root );
//          foreach ( string dir in subdirs )
//          {
//             Scan( dir );        // recursively scan subdir
//          }
//       }

//       ///
//       /// Updates the database info for a file. Assumes the file is an
//       /// MP3 file.
//       ///
//       void _UpdateMP3FileInfo( FileInfo info )
//       {
//          string path = info.FullName;
         
//          // Get ID3 tags from the file

//          CID3v1Tag tag = new CID3v1Tag( path );
//          if (! tag.Read())
//          {
//             // Couldn't read this file's tag. Silently (?) skip.
//             return;
//          }
         
// //          if (tag.Title.Length == 0)
// //          {
// //             // Use the file basename?
// //             // Trace.WriteLine( "Missing info: " + path );
// //          }

//          string genre;
//          if (tag.Genre < ID3_GENRE_TABLE.GetLength(0))
//             genre = ID3_GENRE_TABLE[tag.Genre];
//          else
//             genre = "unknown";

//          if (! Mp3FileEntryExists( path )) // If not already entered,
//          {
//             Trace.WriteLine( "add> " + path );

//             PlayableData data = new PlayableData();
//             data.filePath = path;
//             data.artist = tag.Artist;
//             data.album = tag.Album;
//             data.title = tag.Title;
//             data.track = tag.Track;
//             data.genre = genre;
//             data.lengthInSeconds = 0; // unknown, ID3 tag doesn't know
//             Add( data );
//          }
//       }

      ///
      /// Check to see if the file indicated by fullPath is already
      /// in the database
      ///
      public bool Mp3FileEntryExists( string fullPath )
      {
         // Create a table to hold info derived from the files' own 
         // header info:
         string query = 
            "SELECT count(*) FROM file_info " +
            "  WHERE file_path = '" + _StripEvil( fullPath ) + "'" +
            "  ;";

         IDbConnection dbcon = null;
         IDbCommand cmd = null;
         try
         {
            dbcon = _GetDbConnection();
            cmd = dbcon.CreateCommand();
            cmd.CommandText = query;

            // Returns the first parameter, the number of rows:
            object countObj = cmd.ExecuteScalar();
            int count = Convert.ToInt32( countObj );

            if (count > 0)
               return true;
         }
         catch (Exception e)
         {
            throw new ApplicationException( "Query failed: " + query, e );
         }
         finally
         {
            if (null != cmd)
               cmd.Dispose();

            if (null != dbcon)
               dbcon.Dispose();
         }

         return false;
      }

      ///
      /// Cache all track keys in memory to make a lookup table
      /// to make quick selection of random rows possible.
      ///
      void _UpdateTrackCache( ref PlaylistCriteria criteria )
      {
         // For now, just cache the count. could build in-memory
         // ranked tables for better random weights?
         // if (criteria.cacheTime != _lastModified)
         // {
            criteria.matchCount = GetRowCount( criteria );
            criteria.cacheTime = _lastModified;
         // }
      }

      void _ExecuteNonQuery( string sqlString )
      {
         IDbConnection dbcon = null;
         IDbCommand cmd = null;
         try
         {
            _lastModified = DateTime.Now;

            dbcon = _GetDbConnection();
            cmd = dbcon.CreateCommand();
            cmd.CommandText = sqlString;
            cmd.ExecuteNonQuery();
         }
         catch (Exception e)
         {
            throw new ApplicationException( "Query Failed: " + sqlString, e );
         }
         finally
         {
            if (null != cmd)
               cmd.Dispose();

            if (null != dbcon)
               dbcon.Dispose();
         }
      }

      ///
      /// Close/Dispose of the returned object, OK?
      ///
      IDbConnection _GetDbConnection()
      {
         // Perhaps the one incredibly asinine thing about .NET: you have
         // to hardcode the type of database you are connecting to. Could
         // this be an intentional mistake? Hah.
         IDbConnection dbcon = new SqliteConnection( _connectionString );
         dbcon.Open();
         return dbcon;
      }

      void _Trace( string msg )
      {
         Trace.WriteLine( msg, "StatusDatabase" );
      }


      ///
      /// Time of last database insert or update or whatever. In this
      /// process anyway. :/
      ///
      DateTime _lastModified = DateTime.Now;

      ///
      /// How to connect to our database
      ///
      string _connectionString;

      ///
      /// My local rng
      ///
      Random _rng = new Random();
   }
}

